language: node_js
node_js: 8.13.0
cache: npm

before_deploy: npm run build

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  target-branch: gh-pages
  on:
    branch: master
